<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice CRUD MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						<a href="index.php?route=show_user">Voir les utilisateurs</a>
					</li>
					<li>
						<a href="index.php?route=create_user">Créer une utilisateur</a>
					</li>
					<li>
						<a href="index.php?route=update_user">Mettre à jour les utilisateurs</a>
					</li>
				</ul>
			</nav>
		</header>
		<?php
		if($route === "show_user")
        {   
            require "templates/users/show.phtml";
        }
        
        else if($route === "create_user")
        {
            require "templates/users/create.phtml";
        }
        
        else if($route === "update_user") 
        {
            require "templates/users/update.phtml";
        }
        
        else 
        {
            require "templates/users/list.phtml";
        }
        
		?>
	</body>
</html>